language: python
python:
  - "3.6"
install:
  - python3.6 -m pip install -U pylint
  - python3.6 -m pip install -U git+https://github.com/Rapptz/discord.py@rewrite#egg=discord.py[voice]
  - python3.6 -m pip install bs4
  - python3.6 -m pip install pandas
script:
  - python3.6 test.py
  - if [ $? -eq 0 ]; then (find . -iname "*.py" | xargs python3.6 -m pylint) || exit 0 ; else (find . -iname "*.py" | xargs python3.6 -m pylint) || exit 1; fi;
